platform :ios, '14.0'

target 'CityWalk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # 高德地图轻量版SDK
  pod 'AMapLocation' # 定位SDK
  pod 'AMapSearch', '~> 9.7.4'    # 搜索SDK
  # pod 'AMap3DMap'  # 3D地图SDK

  # config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
  pod 'AMap3DMap', '~> 10.0.600'

end

# 通过 post_install 确保所有 targets 的配置
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
