platform :ios, '14.0'

target 'CityWalk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # 高德地图完整SDK
  pod 'AMapLocation' # 定位SDK
  pod 'AMapSearch', '~> 9.7.4'    # 搜索SDK
  
  # 高德导航SDK (包含MAMapKit和AMapNaviKit)
  pod 'AMapNavi', '~> 10.1.302'   # 导航SDK (包含地图和导航UI组件)

end

# 通过 post_install 确保所有 targets 的配置
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
